/**
 * BCG Matrix Analysis Engine
 *
 * Classifies products/activities into the four BCG quadrants
 * (Star, Cash Cow, Question Mark, Dog) and generates strategic recommendations.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type BcgQuadrant = 'star' | 'cash_cow' | 'question_mark' | 'dog';

export interface ProductData {
  id: string;
  name: string;
  /** Relative market share (0-100). Above 50 = high. */
  marketShare: number;
  /** Market growth rate (percentage, can be negative). Above threshold = high. */
  marketGrowth: number;
  /** Current revenue generated by this product/activity */
  revenue: number;
  /** Optional margin percentage (0-100) */
  margin?: number;
}

export interface BcgClassification {
  product: ProductData;
  quadrant: BcgQuadrant;
  quadrantLabel: string;
  recommendation: string;
  investmentPriority: 'high' | 'medium' | 'low' | 'divest';
  details: string;
}

export interface BcgSummary {
  /** Portfolio balance assessment */
  balanceScore: number;
  balanceDescription: string;
  /** Revenue distribution per quadrant */
  revenueDistribution: Record<BcgQuadrant, number>;
  /** Strategic recommendations for the portfolio */
  portfolioRecommendations: string[];
}

export interface BcgResult {
  classifications: BcgClassification[];
  summary: BcgSummary;
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Market share threshold: above = high, below = low */
const MARKET_SHARE_THRESHOLD = 50;
/** Market growth threshold (%) above which growth is considered high */
const MARKET_GROWTH_THRESHOLD = 10;

const QUADRANT_LABELS: Record<BcgQuadrant, string> = {
  star: 'Étoile (Star)',
  cash_cow: 'Vache à lait (Cash Cow)',
  question_mark: 'Dilemme (Question Mark)',
  dog: 'Poids mort (Dog)',
};

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

/**
 * Classify a product into one of the four BCG quadrants.
 *
 * @param marketShare - Relative market share (0-100)
 * @param marketGrowth - Market growth rate (%)
 * @returns The BCG quadrant
 */
export function classifyProduct(marketShare: number, marketGrowth: number): BcgQuadrant {
  const highShare = marketShare >= MARKET_SHARE_THRESHOLD;
  const highGrowth = marketGrowth >= MARKET_GROWTH_THRESHOLD;

  if (highShare && highGrowth) return 'star';
  if (highShare && !highGrowth) return 'cash_cow';
  if (!highShare && highGrowth) return 'question_mark';
  return 'dog';
}

// ---------------------------------------------------------------------------
// Recommendations
// ---------------------------------------------------------------------------

interface RecommendationContext {
  revenue: number;
  margin: number | undefined;
  marketShare: number;
  marketGrowth: number;
}

function starRecommendation(ctx: RecommendationContext): string {
  const parts: string[] = [
    'Investir massivement pour maintenir la position dominante.',
  ];
  if (ctx.marketGrowth >= 20) {
    parts.push('La croissance forte justifie des investissements soutenus en capacité et marketing.');
  }
  if (ctx.margin !== undefined && ctx.margin < 20) {
    parts.push('Attention : malgré la position de leader, la marge reste faible. Optimiser les coûts opérationnels.');
  }
  return parts.join(' ');
}

function cashCowRecommendation(ctx: RecommendationContext): string {
  const parts: string[] = [
    'Récolter les profits et limiter les investissements au maintien.',
  ];
  if (ctx.marketShare >= 70) {
    parts.push('Position très dominante : utiliser les cash-flows pour financer les Étoiles et Dilemmes.');
  }
  if (ctx.marketGrowth < 0) {
    parts.push('Le marché décline : planifier une transition progressive.');
  }
  return parts.join(' ');
}

function questionMarkRecommendation(ctx: RecommendationContext): string {
  const parts: string[] = [];
  if (ctx.marketGrowth >= 20 && ctx.marketShare >= 30) {
    parts.push('Fort potentiel : investir sélectivement pour gagner des parts de marché et devenir Étoile.');
  } else if (ctx.marketShare < 20) {
    parts.push('Position très faible sur un marché croissant. Évaluer si un investissement massif est justifiable ou envisager le désengagement.');
  } else {
    parts.push('Potentiel incertain : investir de façon ciblée et fixer des jalons de performance clairs.');
  }
  return parts.join(' ');
}

function dogRecommendation(ctx: RecommendationContext): string {
  const parts: string[] = [];
  if (ctx.margin !== undefined && ctx.margin > 30) {
    parts.push('Malgré une faible position, la marge élevée justifie un maintien sélectif sans investissement.');
  } else if (ctx.revenue > 0 && ctx.marketGrowth >= 5) {
    parts.push('Le marché montre des signes de reprise. Envisager un repositionnement de niche avant de désinvestir.');
  } else {
    parts.push('Désinvestir progressivement et réallouer les ressources vers des activités plus porteuses.');
  }
  return parts.join(' ');
}

/**
 * Generate a strategic recommendation for a product based on its BCG quadrant.
 *
 * @param quadrant - The BCG quadrant classification
 * @param product - The product data
 * @returns A strategic recommendation string
 */
export function generateRecommendation(quadrant: BcgQuadrant, product: ProductData): string {
  const ctx: RecommendationContext = {
    revenue: product.revenue,
    margin: product.margin,
    marketShare: product.marketShare,
    marketGrowth: product.marketGrowth,
  };

  switch (quadrant) {
    case 'star':
      return starRecommendation(ctx);
    case 'cash_cow':
      return cashCowRecommendation(ctx);
    case 'question_mark':
      return questionMarkRecommendation(ctx);
    case 'dog':
      return dogRecommendation(ctx);
  }
}

// ---------------------------------------------------------------------------
// Investment priority
// ---------------------------------------------------------------------------

function getInvestmentPriority(quadrant: BcgQuadrant, product: ProductData): 'high' | 'medium' | 'low' | 'divest' {
  switch (quadrant) {
    case 'star':
      return 'high';
    case 'cash_cow':
      return 'low';
    case 'question_mark':
      return product.marketShare >= 30 ? 'medium' : 'low';
    case 'dog':
      return (product.margin ?? 0) > 30 ? 'low' : 'divest';
  }
}

// ---------------------------------------------------------------------------
// Quadrant detail description
// ---------------------------------------------------------------------------

function getQuadrantDetails(quadrant: BcgQuadrant): string {
  switch (quadrant) {
    case 'star':
      return 'Part de marché élevée sur un marché en forte croissance. Nécessite des investissements importants mais génère des revenus croissants.';
    case 'cash_cow':
      return 'Part de marché élevée sur un marché mature. Génère des flux de trésorerie importants avec peu d\'investissement nécessaire.';
    case 'question_mark':
      return 'Faible part de marché sur un marché en croissance. Nécessite des investissements pour gagner des parts ou risque de devenir Poids mort.';
    case 'dog':
      return 'Faible part de marché sur un marché à faible croissance. Génère peu de valeur et consomme des ressources.';
  }
}

// ---------------------------------------------------------------------------
// Portfolio summary
// ---------------------------------------------------------------------------

function assessPortfolio(classifications: BcgClassification[]): BcgSummary {
  const revenueDistribution: Record<BcgQuadrant, number> = {
    star: 0,
    cash_cow: 0,
    question_mark: 0,
    dog: 0,
  };

  const totalRevenue = classifications.reduce((sum, c) => sum + c.product.revenue, 0);

  for (const c of classifications) {
    revenueDistribution[c.quadrant] += totalRevenue > 0
      ? Math.round((c.product.revenue / totalRevenue) * 100)
      : 0;
  }

  const quadrantCounts: Record<BcgQuadrant, number> = { star: 0, cash_cow: 0, question_mark: 0, dog: 0 };
  for (const c of classifications) {
    quadrantCounts[c.quadrant] += 1;
  }

  // Balance score: ideal portfolio has Stars, Cash Cows, and limited Dogs
  let balanceScore = 50; // baseline
  if (quadrantCounts.star > 0) balanceScore += 15;
  if (quadrantCounts.cash_cow > 0) balanceScore += 15;
  if (quadrantCounts.question_mark > 0) balanceScore += 5;
  if (quadrantCounts.dog === 0) balanceScore += 10;
  if (revenueDistribution.dog > 40) balanceScore -= 20;
  if (revenueDistribution.cash_cow > 60 && quadrantCounts.star === 0) balanceScore -= 15;
  balanceScore = Math.max(0, Math.min(100, balanceScore));

  let balanceDescription: string;
  if (balanceScore >= 75) {
    balanceDescription = 'Portefeuille équilibré avec un bon mix de produits générateurs de cash et de croissance.';
  } else if (balanceScore >= 50) {
    balanceDescription = 'Portefeuille partiellement équilibré. Certains ajustements stratégiques sont recommandés.';
  } else {
    balanceDescription = 'Portefeuille déséquilibré nécessitant une restructuration stratégique.';
  }

  const portfolioRecommendations: string[] = [];

  if (quadrantCounts.star === 0 && quadrantCounts.question_mark === 0) {
    portfolioRecommendations.push('Aucun produit en croissance. Risque de déclin à moyen terme. Investir dans de nouvelles activités.');
  }
  if (quadrantCounts.cash_cow === 0) {
    portfolioRecommendations.push('Absence de vache à lait. Risque de manque de financement interne pour la croissance.');
  }
  if (revenueDistribution.dog > 30) {
    portfolioRecommendations.push('Part importante du CA sur des produits Poids mort. Envisager le désinvestissement progressif.');
  }
  if (quadrantCounts.question_mark >= 3) {
    portfolioRecommendations.push('Trop de dilemmes. Prioriser 1-2 produits à fort potentiel et abandonner les autres.');
  }
  if (portfolioRecommendations.length === 0) {
    portfolioRecommendations.push('Le portefeuille est bien positionné. Maintenir l\'équilibre actuel et surveiller les évolutions de marché.');
  }

  return { balanceScore, balanceDescription, revenueDistribution, portfolioRecommendations };
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Generate a complete BCG Matrix analysis for a set of products or activities.
 *
 * @param products - Array of product/activity data to classify
 * @returns Complete BCG analysis with classifications and portfolio summary
 */
export function generateBcgMatrix(products: ProductData[]): BcgResult {
  const classifications: BcgClassification[] = products.map((product) => {
    const quadrant = classifyProduct(product.marketShare, product.marketGrowth);
    return {
      product,
      quadrant,
      quadrantLabel: QUADRANT_LABELS[quadrant],
      recommendation: generateRecommendation(quadrant, product),
      investmentPriority: getInvestmentPriority(quadrant, product),
      details: getQuadrantDetails(quadrant),
    };
  });

  const summary = assessPortfolio(classifications);

  return {
    classifications,
    summary,
    generatedAt: new Date().toISOString(),
  };
}
