// ---------------------------------------------------------------------------
// DiagOptim AI Engine – wraps @anthropic-ai/sdk for all AI interactions
// ---------------------------------------------------------------------------

import Anthropic from "@anthropic-ai/sdk";
import type { CompanyProfile } from "@/types/company";
import type { DocumentType, ExtractedData } from "@/types/document";
import type {
  DiagnosticAnswer,
  DiagnosticFraming,
  WasteCategory,
  WasteScores,
  SWOTData,
  DiagnosticInsight,
  QuestionType,
} from "@/types/diagnostic";
import type { RoadmapAction } from "@/types/roadmap";
import type { ReportLocale } from "@/types/report";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// claude-sonnet-4-20250514 was retired (404). Current capable model, overridable via env.
const MODEL = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-5";
const MAX_RETRIES = 3;
const BASE_DELAY_MS = 1_000;
const DEFAULT_MAX_TOKENS = 4_096;

// ---------------------------------------------------------------------------
// Local types
// ---------------------------------------------------------------------------

/** Context fed to the diagnostic question generator. */
export interface DiagnosticContext {
  companyProfile: CompanyProfile;
  analyzedDocuments: AnalyzedDocumentSummary[];
  previousAnswers: DiagnosticAnswer[];
  currentPhase: DiagnosticPhase;
  framing: DiagnosticFraming;
  locale: ReportLocale;
}

export interface AnalyzedDocumentSummary {
  type: DocumentType;
  summary: string;
  keyFigures: Record<string, number | string>;
}

export type DiagnosticPhase =
  | "framing"
  | "profile"
  | "documents"
  | "wastes"
  | "strategic";

/** Question returned by the AI. */
export interface GeneratedQuestion {
  questionId: string;
  questionText: string;
  questionType: QuestionType;
  options: GeneratedQuestionOption[] | null;
  helpText: string | null;
  skipIf: SkipCondition | null;
  category: WasteCategory | "framing" | "profile" | "documents" | "strategic";
  insight: string | null;
}

export interface GeneratedQuestionOption {
  id: string;
  label: string;
  icon: string | null;
  description: string | null;
}

export interface SkipCondition {
  questionId: string;
  value: unknown;
}

/** Diagnostic data bundle for recommendation generation. */
export interface DiagnosticData {
  companyProfile: CompanyProfile;
  wasteScores: WasteScores;
  swot: SWOTData | null;
  insights: DiagnosticInsight[];
  framing: DiagnosticFraming;
  financialData: FinancialDataSummary | null;
}

export interface FinancialDataSummary {
  annualRevenue: number;
  totalExpenses: number;
  netIncome: number;
  currency: string;
}

/** A generated recommendation. */
export interface Recommendation {
  title: string;
  description: string;
  category: "quick_win" | "short_term" | "structural" | "transformation";
  estimatedImpact: { min: number; max: number; currency: string };
  effortLevel: "low" | "medium" | "high";
  durationWeeks: number;
  wasteCategory: WasteCategory;
  implementationSteps: string[];
  methodology: string;
  priority: number;
}

/** Training content generated by AI. */
export interface TrainingContent {
  title: string;
  type: "video_script" | "memory_sheet" | "implementation_guide";
  sections: TrainingSection[];
  estimatedDurationMinutes: number;
  methodology: string;
}

export interface TrainingSection {
  heading: string;
  body: string;
  keyTakeaways: string[];
}

/** Message structure for the chat function. */
export interface Message {
  role: "user" | "assistant";
  content: string;
}

/** Options for the generic chat function. */
export interface ChatOptions {
  temperature?: number;
  maxTokens?: number;
  stopSequences?: string[];
  /** Override the model for this call (e.g. a faster model for long generations). */
  model?: string;
}

/** Tracks token usage for billing / analytics. */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  model: string;
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Usage tracking (in-memory; plug into your analytics pipeline)
// ---------------------------------------------------------------------------

const usageLog: TokenUsage[] = [];

/**
 * Returns a copy of all recorded token usage entries.
 * Useful for billing dashboards or analytics.
 */
export function getUsageLog(): ReadonlyArray<TokenUsage> {
  return [...usageLog];
}

/** Clears the in-memory usage log. */
export function clearUsageLog(): void {
  usageLog.length = 0;
}

// ---------------------------------------------------------------------------
// Client factory
// ---------------------------------------------------------------------------

let clientSingleton: Anthropic | null = null;

/**
 * Creates (or returns the cached) Anthropic client.
 * Reads `ANTHROPIC_API_KEY` from `process.env`.
 */
export function createClient(): Anthropic {
  if (clientSingleton) return clientSingleton;

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      "Missing ANTHROPIC_API_KEY environment variable. " +
        "Set it in your .env.local file."
    );
  }

  clientSingleton = new Anthropic({ apiKey });
  return clientSingleton;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function recordUsage(
  response: Anthropic.Message
): void {
  usageLog.push({
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
    totalTokens: response.usage.input_tokens + response.usage.output_tokens,
    model: response.model,
    timestamp: new Date().toISOString(),
  });
}

/**
 * Calls the Anthropic API with automatic retries and exponential backoff.
 * @throws after MAX_RETRIES failures.
 */
async function callWithRetry(
  systemPrompt: string,
  messages: Anthropic.MessageParam[],
  options: { temperature: number; maxTokens: number; stopSequences?: string[]; model?: string }
): Promise<Anthropic.Message> {
  const client = createClient();
  let lastError: unknown;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await client.messages.create({
        model: options.model ?? MODEL,
        max_tokens: options.maxTokens,
        temperature: options.temperature,
        system: systemPrompt,
        messages,
        ...(options.stopSequences && options.stopSequences.length > 0
          ? { stop_sequences: options.stopSequences }
          : {}),
      });
      recordUsage(response);
      return response;
    } catch (error: unknown) {
      lastError = error;
      const isRetryable =
        error instanceof Anthropic.RateLimitError ||
        error instanceof Anthropic.InternalServerError ||
        error instanceof Anthropic.APIConnectionError;

      if (!isRetryable || attempt === MAX_RETRIES) {
        throw error;
      }

      const delay = BASE_DELAY_MS * Math.pow(2, attempt - 1);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }

  throw lastError;
}

/**
 * Extracts the text content from an Anthropic message response.
 */
function extractText(response: Anthropic.Message): string {
  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("No text content in AI response.");
  }
  return textBlock.text;
}

/**
 * Parses a JSON string from the AI response, stripping markdown fences if present.
 */
export function parseJSON<T>(raw: string): T {
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
  return JSON.parse(cleaned) as T;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates the next diagnostic question based on the current context.
 * Returns a structured question object ready for UI rendering.
 */
export async function generateDiagnosticQuestion(
  context: DiagnosticContext
): Promise<GeneratedQuestion> {
  // Dynamically import the prompt builder
  const { buildDiagnosticPrompt } = await import("./prompts/diagnostic");

  const systemPrompt = buildDiagnosticPrompt(context);

  const userMessage =
    context.previousAnswers.length === 0
      ? "Commence le diagnostic. Pose la premiere question."
      : `Voici la derniere reponse: ${JSON.stringify(
          context.previousAnswers[context.previousAnswers.length - 1]
        )}. Pose la question suivante.`;

  const response = await callWithRetry(
    systemPrompt,
    [{ role: "user", content: userMessage }],
    { temperature: 0.4, maxTokens: 2_048 }
  );

  const text = extractText(response);
  return parseJSON<GeneratedQuestion>(text);
}

/**
 * Analyzes an uploaded document and extracts structured data.
 * @param content - The text content of the document (from OCR or direct extraction).
 * @param type - The type of document being analyzed.
 */
export async function analyzeDocument(
  content: string,
  type: DocumentType
): Promise<ExtractedData> {
  const { getDocumentAnalysisPrompt } = await import(
    "./prompts/document-analysis"
  );

  const systemPrompt = getDocumentAnalysisPrompt(type);

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: `Analyse le document suivant et extrais les donnees structurees:\n\n${content}`,
      },
    ],
    { temperature: 0.1, maxTokens: 4_096 }
  );

  const text = extractText(response);
  return parseJSON<ExtractedData>(text);
}

/**
 * Generates prioritized recommendations based on full diagnostic data.
 * Recommendations include financial impact estimates and implementation steps.
 */
export async function generateRecommendations(
  diagnosticData: DiagnosticData
): Promise<Recommendation[]> {
  const { buildRecommendationsPrompt } = await import(
    "./prompts/recommendations"
  );

  const systemPrompt = buildRecommendationsPrompt();

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify(diagnosticData),
      },
    ],
    { temperature: 0.3, maxTokens: 8_192 }
  );

  const text = extractText(response);
  return parseJSON<Recommendation[]>(text);
}

/**
 * Generates a high-level insight summary from the current answers and company profile.
 * Used to display real-time feedback during the diagnostic conversation.
 */
export async function generateInsight(
  answers: DiagnosticAnswer[],
  companyProfile: CompanyProfile
): Promise<string> {
  const systemPrompt = `Tu es un consultant expert en Lean Management et Six Sigma pour DiagOptim.
A partir des reponses du diagnostic et du profil de l'entreprise, genere un insight court et actionnable (2-3 phrases max).
L'insight doit etre encourageant et orienter vers une piste d'amelioration concrete.
Reponds uniquement avec le texte de l'insight, sans formatage JSON.`;

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify({ answers, companyProfile }),
      },
    ],
    { temperature: 0.5, maxTokens: 512 }
  );

  return extractText(response);
}

/**
 * Generates micro-training content (video script, memory sheet, or implementation guide)
 * tailored to a specific roadmap action and methodology.
 */
export async function generateTrainingContent(
  action: RoadmapAction,
  methodology: string
): Promise<TrainingContent> {
  const { buildTrainingContentPrompt } = await import(
    "./prompts/training-content"
  );

  const systemPrompt = buildTrainingContentPrompt();

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify({ action, methodology }),
      },
    ],
    { temperature: 0.4, maxTokens: 8_192 }
  );

  const text = extractText(response);
  return parseJSON<TrainingContent>(text);
}

/**
 * Generic chat function for free-form AI interactions.
 * Supports custom system prompts, message history, and generation options.
 */
export async function chat(
  systemPrompt: string,
  messages: Message[],
  options?: ChatOptions
): Promise<string> {
  const temperature = options?.temperature ?? 0.5;
  const maxTokens = options?.maxTokens ?? DEFAULT_MAX_TOKENS;
  const stopSequences = options?.stopSequences;

  const anthropicMessages: Anthropic.MessageParam[] = messages.map((m) => ({
    role: m.role,
    content: m.content,
  }));

  const response = await callWithRetry(systemPrompt, anthropicMessages, {
    temperature,
    maxTokens,
    stopSequences,
    model: options?.model,
  });

  return extractText(response);
}

// ---------------------------------------------------------------------------
// Adaptive scoping follow-up generator
// ---------------------------------------------------------------------------

/**
 * Indirection wrapper around {@link chat}.
 *
 * `generateScopingFollowUp` calls the AI through `scopingAiDeps.chat` rather than
 * the bare `chat` binding so unit tests can stub the call
 * (`vi.spyOn(scopingAiDeps, "chat")`) and stay fully hermetic — no real network
 * request is ever made in tests.
 */
export const scopingAiDeps = { chat };

export interface ScopingFollowUpInput {
  questionTextFr: string;
  category: string; // 6M tag: man|machine|method|material|measurement|environment|framing
  answer: string;
  sector?: string;
}

/**
 * Given a scoping answer, returns at most ONE short French follow-up question to
 * dig deeper (5-Whys style) when the answer opens an automation lead or a
 * grievance worth exploring — otherwise null.
 */
export async function generateScopingFollowUp(
  input: ScopingFollowUpInput,
): Promise<{ followUp: string | null }> {
  const systemPrompt = `Tu es un consultant qui cadre un projet d'automatisation et d'agent IA pour une PME.
A partir de la question posee et de la reponse d'un collaborateur, genere AU PLUS UNE question de relance:
- courte, concrete, en francais, ton conversationnel, sans jargon Lean;
- pour creuser une piste d'automatisation ou une doleance (technique des 5 Pourquoi si pertinent);
- UNIQUEMENT si la reponse ouvre vraiment une piste. Si la reponse est vague, vide ou deja complete, renvoie null.
Reponds STRICTEMENT en JSON: {"followUp": "..."} ou {"followUp": null}. Rien d'autre.`;

  const userMessage = JSON.stringify({
    question: input.questionTextFr,
    categorie6M: input.category,
    reponse: input.answer,
    secteur: input.sector ?? null,
  });

  const raw = await scopingAiDeps.chat(
    systemPrompt,
    [{ role: "user", content: userMessage }],
    {
      temperature: 0.4,
      maxTokens: 256,
    },
  );
  const parsed = parseJSON<{ followUp: string | null }>(raw);
  return { followUp: parsed.followUp ?? null };
}

// ---------------------------------------------------------------------------
// Per-respondent viewpoint summary generator
// ---------------------------------------------------------------------------

export interface RespondentAnswer {
  questionTextFr: string;
  category: string; // 6M tag
  answer: string;
}

export interface RespondentSummary {
  summary: string;                                   // 2-4 sentences, French
  painPoints: Array<{ text: string; category: string }>; // grievances tagged by 6M
}

/**
 * Condenses one stakeholder's scoping answers into a short French viewpoint
 * summary plus a list of pain points tagged by 6M category. Feeds the
 * consolidated Ishikawa/A3 (SP4).
 */
export async function summarizeRespondentViewpoint(
  answers: RespondentAnswer[],
  sector?: string,
): Promise<RespondentSummary> {
  const systemPrompt = `Tu es un consultant qui cadre un projet d'automatisation et d'agent IA pour une PME.
A partir des reponses d'UN collaborateur a un questionnaire structure par les 6M (Main d'oeuvre, Machines, Methodes, Matieres, Mesure, Milieu), produis:
- "summary": 2 a 4 phrases en francais resumant son point de vue et ses principales doleances;
- "painPoints": la liste de ses points de douleur concrets, chacun avec sa categorie 6M (man|machine|method|material|measurement|environment).
Reste fidele a ses reponses, ne rien inventer. Ton factuel.
Reponds STRICTEMENT en JSON: {"summary": "...", "painPoints": [{"text": "...", "category": "..."}]}.`;
  const userMessage = JSON.stringify({ secteur: sector ?? null, reponses: answers });
  const raw = await scopingAiDeps.chat(systemPrompt, [{ role: "user", content: userMessage }], {
    temperature: 0.3,
    maxTokens: 1024,
  });
  const parsed = parseJSON<RespondentSummary>(raw);
  return {
    summary: parsed.summary ?? "",
    painPoints: Array.isArray(parsed.painPoints) ? parsed.painPoints : [],
  };
}

// ---------------------------------------------------------------------------
// Consolidated scoping synthesis (A3 boxes 1-4 + Ishikawa 6M + cahier des charges)
// ---------------------------------------------------------------------------

export interface RespondentBundle {
  role: string;
  answers: Array<{ question: string; category: string; answer: string }>;
}
export interface ScopingSynthesis {
  a3: { background: string; problemStatement: string; goal: string; rootCauseAnalysis: string };
  ishikawa: {
    problem: string;
    causes: { man: string[]; machine: string[]; method: string[]; material: string[]; measurement: string[]; environment: string[] };
    rootCause: string;
  };
  cahierDesCharges: {
    contexte: string;
    perimetre: string;
    tachesAAutomatiser: Array<{ tache: string; frequence: string; priorite: string }>;
    casUsageAgentIA: Array<{ processus: string; usage: string; causesTraitees: string }>;
    donneesEtIntegrations: string;
    contraintesEtRisques: string;
    pointsDeVueParRole: Array<{ role: string; synthese: string }>;
    priorisation: string;
    criteresDeRecette: string;
  };
  /**
   * Strategic layer (SP-STRAT-3) — present ONLY when direction-level respondents
   * answered the gated STEEPLE / Hoshin / SWOT / SBS blocks. Each sub-section is
   * optional so the exports render nothing when it wasn't collected.
   */
  strategic?: {
    steeple?: { social: string; technological: string; economic: string; environmental: string; political: string; legal: string; ethical: string };
    swot?: { strengths: string[]; weaknesses: string[]; opportunities: string[]; threats: string[] };
    hoshin?: { objective: string; trueNorth: string; breakthroughs: string[]; alignment: string };
    sbs?: { valueStream: string; rationale: string };
  };
  /**
   * Automation-suitability layer (Tier 5) — scores each candidate task on volume,
   * standardisation and rules-vs-judgment, yielding an automatability score + the
   * right human-in-the-loop mode, plus a data-readiness read. Optional for backward
   * compatibility with syntheses generated before this field existed.
   */
  automatisation?: {
    taches: Array<{
      tache: string;
      volume: "faible" | "moyen" | "eleve";
      standardisation: "faible" | "moyenne" | "elevee";
      nature: "regles" | "mixte" | "jugement";
      score: number; // 0-100 automatability
      mode: "automatisable" | "assiste" | "humain"; // full auto / AI-assisted / human-in-the-loop
    }>;
    dataReadiness: string;
    synthese: string;
  };
}

export async function generateScopingSynthesis(
  projectName: string,
  companyName: string,
  respondents: RespondentBundle[],
): Promise<ScopingSynthesis> {
  const systemPrompt = `Tu es un consultant en excellence operationnelle et automatisation IA (methode A3 + Ishikawa 6M).
A partir des avis de PLUSIEURS parties prenantes d'une PME (chacun avec son role et ses reponses taguees 6M: man=Main d'oeuvre, machine=Machines, method=Methodes, material=Matieres, measurement=Mesure, environment=Milieu), produis une analyse consolidee et un cahier des charges d'automatisation / agent IA.
Regles: reste fidele aux avis (ne rien inventer), croise les points de vue (fais ressortir convergences et divergences par role), va jusqu'a l'analyse des causes racines.
Les reponses des repondants comportent une caracterisation 5W2H (Quoi/Quand/Pourquoi/Combien) du processus cible: sers-t'en pour preciser le problemStatement (case 2 de l'A3) et le goal / objectif (case 3).
Les reponses sondent aussi les 8 gaspillages Lean (TIMWOODS: Transport, Stocks/Inventory, Mouvements/Motion, Attentes/Waiting, Surproduction/Overproduction, Sur-traitement/Overprocessing, Defauts/Defects, Competences/Skills): identifie explicitement quels gaspillages sont presents et refletes-les dans le rootCauseAnalysis (case 4 de l'A3) et dans les causes de l'Ishikawa.
COUCHE STRATEGIQUE (optionnelle): certains repondants de niveau direction ont pu repondre a des blocs taggues "steeple" (Societe/Technologie/Economie/Environnement/Politique/Legal/Ethique), "hoshin" (objectif strategique 12-18 mois, indicateur True North vise, percees prioritaires), "swot" (Forces/Faiblesses/Opportunites/Menaces) et "sbs" (chaine de valeur SBS: demand/delivery/development/support).
- Si de telles reponses existent, produis la clef "strategic" avec les sous-sections correspondantes; sinon N'INCLUS PAS du tout la clef "strategic".
- Utilise l'objectif Hoshin pour PRECISER le goal (case 3 de l'A3) et pour ORDONNER la priorisation de facon descendante (la roadmap doit servir l'objectif strategique). "alignment" = une phrase reliant explicitement le projet a l'objectif strategique et a l'indicateur True North.
- Utilise le contexte STEEPLE pour enrichir le background (case 1 de l'A3).
- "sbs.valueStream" doit valoir exactement l'une de: demand, delivery, development, support.
COUCHE AUTOMATISABILITE (toujours produite): pour CHAQUE tache de "tachesAAutomatiser", evalue son potentiel d'automatisation par IA et produis un objet dans "automatisation.taches":
- "volume" (faible|moyen|eleve) = frequence/volume du processus (sers-toi des reponses 5W2H Quand/Combien).
- "standardisation" (faible|moyenne|elevee) = degre de standardisation/repetabilite (une tache reglee et repetitive = elevee; une tache qui varie a chaque fois = faible).
- "nature" (regles|mixte|jugement) = la tache repose-t-elle sur des regles claires, un melange, ou du jugement humain ?
- "score" (0-100) = automatisabilite globale (eleve si volume eleve + standardisation elevee + regles).
- "mode": "automatisable" (bon candidat automatisation complete), "assiste" (l'IA assiste, l'humain valide), ou "humain" (garder l'humain dans la boucle: jugement/relationnel/risque).
Ajoute "automatisation.dataReadiness" (les donnees necessaires sont-elles disponibles, structurees, accessibles ? points de vigilance) et "automatisation.synthese" (1-2 phrases: par quoi commencer et pourquoi).
N'utilise AUCUN formatage Markdown dans les valeurs (pas de **, pas de #, pas de backticks): texte brut uniquement.
Reponds STRICTEMENT en JSON conforme a ce schema (aucun texte hors JSON):
{"a3":{"background":"...","problemStatement":"...","goal":"...","rootCauseAnalysis":"..."},
 "automatisation":{"taches":[{"tache":"...","volume":"moyen","standardisation":"elevee","nature":"regles","score":80,"mode":"automatisable"}],"dataReadiness":"...","synthese":"..."},
 "ishikawa":{"problem":"...","causes":{"man":["..."],"machine":["..."],"method":["..."],"material":["..."],"measurement":["..."],"environment":["..."]},"rootCause":"..."},
 "cahierDesCharges":{"contexte":"...","perimetre":"...","tachesAAutomatiser":[{"tache":"...","frequence":"...","priorite":"..."}],"casUsageAgentIA":[{"processus":"...","usage":"...","causesTraitees":"..."}],"donneesEtIntegrations":"...","contraintesEtRisques":"...","pointsDeVueParRole":[{"role":"...","synthese":"..."}],"priorisation":"...","criteresDeRecette":"..."},
 "strategic":{"steeple":{"social":"...","technological":"...","economic":"...","environmental":"...","political":"...","legal":"...","ethical":"..."},"swot":{"strengths":["..."],"weaknesses":["..."],"opportunities":["..."],"threats":["..."]},"hoshin":{"objective":"...","trueNorth":"...","breakthroughs":["..."],"alignment":"..."},"sbs":{"valueStream":"delivery","rationale":"..."}}}`;
  const userMessage = JSON.stringify({ projet: projectName, entreprise: companyName, parties_prenantes: respondents });
  // Haiku 4.5: this is a long structured generation (~55s on Sonnet -> Vercel timeout);
  // Haiku keeps it ~20s, safely within the function budget.
  const raw = await scopingAiDeps.chat(systemPrompt, [{ role: "user", content: userMessage }], {
    temperature: 0.3,
    maxTokens: 8192,
    model: "claude-haiku-4-5-20251001",
  });
  return parseJSON<ScopingSynthesis>(raw);
}
