// ---------------------------------------------------------------------------
// DiagOptim AI Engine – wraps @anthropic-ai/sdk for all AI interactions
// ---------------------------------------------------------------------------

import Anthropic from "@anthropic-ai/sdk";
import type { CompanyProfile } from "@/types/company";
import type { DocumentType, ExtractedData } from "@/types/document";
import type {
  DiagnosticAnswer,
  DiagnosticFraming,
  WasteCategory,
  WasteScores,
  SWOTData,
  DiagnosticInsight,
  QuestionType,
} from "@/types/diagnostic";
import type { RoadmapAction } from "@/types/roadmap";
import type { ReportLocale } from "@/types/report";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MODEL = "claude-sonnet-4-20250514";
const MAX_RETRIES = 3;
const BASE_DELAY_MS = 1_000;
const DEFAULT_MAX_TOKENS = 4_096;

// ---------------------------------------------------------------------------
// Local types
// ---------------------------------------------------------------------------

/** Context fed to the diagnostic question generator. */
export interface DiagnosticContext {
  companyProfile: CompanyProfile;
  analyzedDocuments: AnalyzedDocumentSummary[];
  previousAnswers: DiagnosticAnswer[];
  currentPhase: DiagnosticPhase;
  framing: DiagnosticFraming;
  locale: ReportLocale;
}

export interface AnalyzedDocumentSummary {
  type: DocumentType;
  summary: string;
  keyFigures: Record<string, number | string>;
}

export type DiagnosticPhase =
  | "framing"
  | "profile"
  | "documents"
  | "wastes"
  | "strategic";

/** Question returned by the AI. */
export interface GeneratedQuestion {
  questionId: string;
  questionText: string;
  questionType: QuestionType;
  options: GeneratedQuestionOption[] | null;
  helpText: string | null;
  skipIf: SkipCondition | null;
  category: WasteCategory | "framing" | "profile" | "documents" | "strategic";
  insight: string | null;
}

export interface GeneratedQuestionOption {
  id: string;
  label: string;
  icon: string | null;
  description: string | null;
}

export interface SkipCondition {
  questionId: string;
  value: unknown;
}

/** Diagnostic data bundle for recommendation generation. */
export interface DiagnosticData {
  companyProfile: CompanyProfile;
  wasteScores: WasteScores;
  swot: SWOTData | null;
  insights: DiagnosticInsight[];
  framing: DiagnosticFraming;
  financialData: FinancialDataSummary | null;
}

export interface FinancialDataSummary {
  annualRevenue: number;
  totalExpenses: number;
  netIncome: number;
  currency: string;
}

/** A generated recommendation. */
export interface Recommendation {
  title: string;
  description: string;
  category: "quick_win" | "short_term" | "structural" | "transformation";
  estimatedImpact: { min: number; max: number; currency: string };
  effortLevel: "low" | "medium" | "high";
  durationWeeks: number;
  wasteCategory: WasteCategory;
  implementationSteps: string[];
  methodology: string;
  priority: number;
}

/** Training content generated by AI. */
export interface TrainingContent {
  title: string;
  type: "video_script" | "memory_sheet" | "implementation_guide";
  sections: TrainingSection[];
  estimatedDurationMinutes: number;
  methodology: string;
}

export interface TrainingSection {
  heading: string;
  body: string;
  keyTakeaways: string[];
}

/** Message structure for the chat function. */
export interface Message {
  role: "user" | "assistant";
  content: string;
}

/** Options for the generic chat function. */
export interface ChatOptions {
  temperature?: number;
  maxTokens?: number;
  stopSequences?: string[];
}

/** Tracks token usage for billing / analytics. */
export interface TokenUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  model: string;
  timestamp: string;
}

// ---------------------------------------------------------------------------
// Usage tracking (in-memory; plug into your analytics pipeline)
// ---------------------------------------------------------------------------

const usageLog: TokenUsage[] = [];

/**
 * Returns a copy of all recorded token usage entries.
 * Useful for billing dashboards or analytics.
 */
export function getUsageLog(): ReadonlyArray<TokenUsage> {
  return [...usageLog];
}

/** Clears the in-memory usage log. */
export function clearUsageLog(): void {
  usageLog.length = 0;
}

// ---------------------------------------------------------------------------
// Client factory
// ---------------------------------------------------------------------------

let clientSingleton: Anthropic | null = null;

/**
 * Creates (or returns the cached) Anthropic client.
 * Reads `ANTHROPIC_API_KEY` from `process.env`.
 */
export function createClient(): Anthropic {
  if (clientSingleton) return clientSingleton;

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error(
      "Missing ANTHROPIC_API_KEY environment variable. " +
        "Set it in your .env.local file."
    );
  }

  clientSingleton = new Anthropic({ apiKey });
  return clientSingleton;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function recordUsage(
  response: Anthropic.Message
): void {
  usageLog.push({
    inputTokens: response.usage.input_tokens,
    outputTokens: response.usage.output_tokens,
    totalTokens: response.usage.input_tokens + response.usage.output_tokens,
    model: response.model,
    timestamp: new Date().toISOString(),
  });
}

/**
 * Calls the Anthropic API with automatic retries and exponential backoff.
 * @throws after MAX_RETRIES failures.
 */
async function callWithRetry(
  systemPrompt: string,
  messages: Anthropic.MessageParam[],
  options: { temperature: number; maxTokens: number; stopSequences?: string[] }
): Promise<Anthropic.Message> {
  const client = createClient();
  let lastError: unknown;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      const response = await client.messages.create({
        model: MODEL,
        max_tokens: options.maxTokens,
        temperature: options.temperature,
        system: systemPrompt,
        messages,
        ...(options.stopSequences && options.stopSequences.length > 0
          ? { stop_sequences: options.stopSequences }
          : {}),
      });
      recordUsage(response);
      return response;
    } catch (error: unknown) {
      lastError = error;
      const isRetryable =
        error instanceof Anthropic.RateLimitError ||
        error instanceof Anthropic.InternalServerError ||
        error instanceof Anthropic.APIConnectionError;

      if (!isRetryable || attempt === MAX_RETRIES) {
        throw error;
      }

      const delay = BASE_DELAY_MS * Math.pow(2, attempt - 1);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }

  throw lastError;
}

/**
 * Extracts the text content from an Anthropic message response.
 */
function extractText(response: Anthropic.Message): string {
  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") {
    throw new Error("No text content in AI response.");
  }
  return textBlock.text;
}

/**
 * Parses a JSON string from the AI response, stripping markdown fences if present.
 */
function parseJSON<T>(raw: string): T {
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
  return JSON.parse(cleaned) as T;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generates the next diagnostic question based on the current context.
 * Returns a structured question object ready for UI rendering.
 */
export async function generateDiagnosticQuestion(
  context: DiagnosticContext
): Promise<GeneratedQuestion> {
  // Dynamically import the prompt builder
  const { buildDiagnosticPrompt } = await import("./prompts/diagnostic");

  const systemPrompt = buildDiagnosticPrompt(context);

  const userMessage =
    context.previousAnswers.length === 0
      ? "Commence le diagnostic. Pose la premiere question."
      : `Voici la derniere reponse: ${JSON.stringify(
          context.previousAnswers[context.previousAnswers.length - 1]
        )}. Pose la question suivante.`;

  const response = await callWithRetry(
    systemPrompt,
    [{ role: "user", content: userMessage }],
    { temperature: 0.4, maxTokens: 2_048 }
  );

  const text = extractText(response);
  return parseJSON<GeneratedQuestion>(text);
}

/**
 * Analyzes an uploaded document and extracts structured data.
 * @param content - The text content of the document (from OCR or direct extraction).
 * @param type - The type of document being analyzed.
 */
export async function analyzeDocument(
  content: string,
  type: DocumentType
): Promise<ExtractedData> {
  const { getDocumentAnalysisPrompt } = await import(
    "./prompts/document-analysis"
  );

  const systemPrompt = getDocumentAnalysisPrompt(type);

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: `Analyse le document suivant et extrais les donnees structurees:\n\n${content}`,
      },
    ],
    { temperature: 0.1, maxTokens: 4_096 }
  );

  const text = extractText(response);
  return parseJSON<ExtractedData>(text);
}

/**
 * Generates prioritized recommendations based on full diagnostic data.
 * Recommendations include financial impact estimates and implementation steps.
 */
export async function generateRecommendations(
  diagnosticData: DiagnosticData
): Promise<Recommendation[]> {
  const { buildRecommendationsPrompt } = await import(
    "./prompts/recommendations"
  );

  const systemPrompt = buildRecommendationsPrompt();

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify(diagnosticData),
      },
    ],
    { temperature: 0.3, maxTokens: 8_192 }
  );

  const text = extractText(response);
  return parseJSON<Recommendation[]>(text);
}

/**
 * Generates a high-level insight summary from the current answers and company profile.
 * Used to display real-time feedback during the diagnostic conversation.
 */
export async function generateInsight(
  answers: DiagnosticAnswer[],
  companyProfile: CompanyProfile
): Promise<string> {
  const systemPrompt = `Tu es un consultant expert en Lean Management et Six Sigma pour DiagOptim.
A partir des reponses du diagnostic et du profil de l'entreprise, genere un insight court et actionnable (2-3 phrases max).
L'insight doit etre encourageant et orienter vers une piste d'amelioration concrete.
Reponds uniquement avec le texte de l'insight, sans formatage JSON.`;

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify({ answers, companyProfile }),
      },
    ],
    { temperature: 0.5, maxTokens: 512 }
  );

  return extractText(response);
}

/**
 * Generates micro-training content (video script, memory sheet, or implementation guide)
 * tailored to a specific roadmap action and methodology.
 */
export async function generateTrainingContent(
  action: RoadmapAction,
  methodology: string
): Promise<TrainingContent> {
  const { buildTrainingContentPrompt } = await import(
    "./prompts/training-content"
  );

  const systemPrompt = buildTrainingContentPrompt();

  const response = await callWithRetry(
    systemPrompt,
    [
      {
        role: "user",
        content: JSON.stringify({ action, methodology }),
      },
    ],
    { temperature: 0.4, maxTokens: 8_192 }
  );

  const text = extractText(response);
  return parseJSON<TrainingContent>(text);
}

/**
 * Generic chat function for free-form AI interactions.
 * Supports custom system prompts, message history, and generation options.
 */
export async function chat(
  systemPrompt: string,
  messages: Message[],
  options?: ChatOptions
): Promise<string> {
  const temperature = options?.temperature ?? 0.5;
  const maxTokens = options?.maxTokens ?? DEFAULT_MAX_TOKENS;
  const stopSequences = options?.stopSequences;

  const anthropicMessages: Anthropic.MessageParam[] = messages.map((m) => ({
    role: m.role,
    content: m.content,
  }));

  const response = await callWithRetry(systemPrompt, anthropicMessages, {
    temperature,
    maxTokens,
    stopSequences,
  });

  return extractText(response);
}
